framework:
  workflows:
    job_workflow:
      type: "state_machine"
      audit_trail:
        enabled: true
      marking_store:
        type: "method"
        property: "status"
      supports:
        - App\Entity\Job
      initial_marking: draft
      places:
        - draft
        - published
        - paused
        - closed
      transitions:
        publish:
          from: draft
          to: published
        pause:
          from: published
          to: paused
        resume:
          from: paused
          to: published
        close:
          from: [draft, published, paused]
          to: closed

    job_application_workflow:
      type: "state_machine"
      marking_store:
        type: "method"
        property: "status"
      supports:
        - App\Entity\Application
      initial_marking: "applied"
      places:
        - applied
        - shortlisted
        - interviewing
        - negotiating
        - accepted
        - completed
        - rejected
      transitions:
        shortlist:
          from: [applied, interviewing, negotiating, accepted, completed, rejected]
          to: shortlisted
        interview:
          from: [applied, shortlisted, negotiating, accepted, completed, rejected]
          to: interviewing
        negotiate:
          from: [applied, shortlisted, interviewing, accepted, completed, rejected]
          to: negotiating
        accept:
          from: [applied, shortlisted, interviewing, negotiating, completed, rejected]
          to: accepted
        complete:
          from: [applied, shortlisted, interviewing, negotiating, accepted, rejected]
          to: completed
        reject:
          from: [applied, shortlisted, interviewing, negotiating, accepted, completed]
          to: rejected
        move_to_applied:
          from: [shortlisted, interviewing, negotiating, accepted, completed, rejected]
          to: applied
